logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG
spring:
  datasource:
    url:  jdbc:h2:file:./h2/org2
#  url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true